[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dippy"
version = "0.1.0"  # Static version number
description = "Dippy Subnet Validation API"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "dippy.ai", email = "dknoller@fastmail.com"}
]
classifiers = [
    "Development Status :: Sigma",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/impel-intelligence/dippy-bittensor-subnet"

[tool.setuptools.packages.find]
where = ["."]
include = ["scoring*", "common*", "constants*", "utilities*", "template*", "model*", "dippy_validation_api*"]
exclude = ["tests*"]

[tool.setuptools]
include-package-data = true

[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 120